@uri = http://localhost:{{ $dotenv PORT }}

@cookie = token_data=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuIjoiZXlKamIyNTBaVzUwSWpvaVQzQklWVFJSZDNWaFRXMXZaMFpTTW1aRVQySXhOMnhLSzJKTlJUVnJPVVJxVlVsRlJYZDRTbXRxV1hJNGFWQllObGd4YTNGbWNERk9Xa2RzU2pSR2NtYzRia1F5VTFkRVMwaHlRV2xPU0VoSlVXTmtWamh2ZERKc1VVTk1SR1JMUVdOc2FGRkZTRVJIY2xScU1WUk1hMFI0TVhGeFlYbHZkSEJqVlhVMmRYcFdNR0ZKZUc5MlRXTXdXVTVEYURaUFZHNVVaV0pYU21WeGJtOXlaVGRQVWs1VGQxbDBZVUpaVFROUmRVWkpTbWN2TVZKcU5uSXZUMFJwWjJSUmNrbE5JbjA9In0sImlhdCI6MTY1NTEwNTUxMywiZXhwIjoxNjU1MTIzNTEzLCJpc3MiOiJjdG91dHdlYiIsInN1YiI6ImNzdXJmX3Rva2VuIiwianRpIjoiMjI4NDQzOTAtYjAxMi00ZjlhLWJlNDAtOGI5NWVhZDEwMGYwIn0.ctC-Qb5gXoz5MVilTbU3M7S_kBv-y1EZyLtnvQOWsro

POST {{uri}}/api/messaging
Cookie: {{cookie}}
Content-Type: application/json

{
    "reason": "je souhaite faire un nouveau devis",
    "email": "aviateur22@hotmail.fr",
    "name":"bob l'éponge le 1er du nom",
    "phone": "0623274101",    
    "message": "bonjour, comment vas tu. Moi je vais très bien. Que fais tu de beau? moi je ne fais rien; ou bien je fais plein : de test - A -B -_VC",
    "token": "eyJjb250ZW50IjoibHR6dUhUU2FhSWd6VVhrSEdheklxY2Uwb1RJc0JnSG9XSGFaS3dlUDZTeHM5MGh1NkV0dmo4V2tCakJSOFdLQyJ9"
}


###

GET {}