@uri = http://localhost:{{ $dotenv PORT }}

@cookie = token_data=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InRva2VuIjoiZXlKamIyNTBaVzUwSWpvaWIzUlRTR3RRV0d4aWRHOXpXR1UzV1d0WWVVcFhTMUZMZWxsVk5YQnJkekJPYTJjM1MyWkNSVEZMY0dWeFpVSklNRmRDUm5sc0wzWjVTbEpLTDNOcE1ERXdSbW95TTBoRlFqTk5kSGxXU2psalNEWk1WalY2WWxGU1NFUlZUbVZTYnpScFpHTjZaWEZRZWxOa2VrRlJNME0xYm5KTlMwTm1WSEJ6TTJWMlMwTXpWVTltZDFoNmQxcGhlbFp0T1dKV1Fsa3JXbnBVUmpWWFVIa3laaXN3VTFGeE0wcG5kR2xzVW10RE5tOVRlSGRSVjNwaFowTXliRWwyVEhSeVVGaG5JbjA9In0sImlhdCI6MTY1NjAxODE3NywiZXhwIjoxNjU2MDM2MTc3LCJpc3MiOiJjdG91dHdlYiIsInN1YiI6ImNzdXJmX3Rva2VuIiwianRpIjoiNWFkZTE2OTktYjc1NS00MDcyLWIzNTMtMDcyYzlmY2Y3NmFiIn0.nPWziuvYsV1axWCmnxsetaTqP7D0ro_UIcFrvh3Aw3Y

POST {{uri}}/api/messaging
Cookie: {{cookie}}
Content-Type: application/json

{
    "reason": "je souhaite faire un nouveau devis",
    "email": "aviateur22@hotmail.fr",
    "name":"bob l'éponge le 1er du nom",
    "phone": "0623274101",    
    "message": "bonjour, comment vas tu. Moi je vais très bien. Que fais tu de beau? moi je ne fais rien; ou bien je fais plein : de test - A -B -_VC",
    "token": "eyJjb250ZW50Ijoib2EzS01mWmFCNmxubUxlcXo5ZTBOL2xkVlZOZzlMMkQ0RW8xbmlNQWJBS1p5SHF6QlVTZUNEU3ZRMTVwdGVlbCJ9"    
}
